[versions]
agp = "7.0.0-beta04"
sdk-min = "21"
sdk-target = "30"
sdk-compile = "30"
buildTools = "30.0.3"
coroutines = "1.5.0"
compose = "1.0.0-rc01"
androidx-activity = "1.3.0-rc01"
accompanist = "0.13.0"
jUnit = "4.13.2"
truth = "1.1.3"
testExt = "1.1.1"
espresso = "3.2.0"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-coil = { module = "com.google.accompanist:accompanist-coil", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
jUnit = { module = "junit:junit", version.ref = "jUnit" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
testExt = { module = "androidx.test.ext:junit", version.ref = "testExt" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[bundles]
compose = ["compose-foundation", "compose-material"]
accompanist = ["accompanist-insets", "accompanist-coil", "accompanist-pager"]
